@startuml practica2_reto_f

header "Representacion de clases"
title "Juegos Panamericanos"
    

abstract Persona  {
    -nombre
    -telefono
    -direccion
} 
class Entrenador{
    -nivel
    -experiencia
}

class Juego {
    -Localidad
    -Puntuacion
}

class Equipo{
    -nombre
    -pais

}

class Registro {
    -idJugador
    -Record
}

class Jugador {
    -numero
    -posicion
}

Class Capitan

Equipo "1" o-right-"6..20" Jugador: Parte de <
Equipo *--  Registro
Persona <|-- Jugador
Persona <|-left- Entrenador: Hereda de <
Juego "1" *-right- "2" Equipo: Parte de un <
Equipo "<b>*" *-up- "<b> 1 " Entrenador: Compone a <
Competencia *-- Juego
Capitan --|> Jugador: Hereda de > 
Capitan "1" --* "1" Equipo: Compone a >

newpage 
'left to right direction
'right to left direccion
/'
package Venezuela{
    object Entrenador{
        "Entrenador 1"
    }

    package integrantes {
        object Jugador1{
            "pepe1"
            213123123
            La Guaira
        }
        object Jugador2{
            "pepe2"
            213123123
            La Guaira
        }
        object Jugador3{
            "pepe3"
            213123123
            La Guaira
        }
        object Jugador4{
            "pepe4"
            213123123
            La Guaira
        }
        object Jugador5{
            "pepe5"
            213123123
            La Guaira
        }
        object Capitan6{
            "pepe6"
            213123123
            La Guaira
        }
    }
}


package Colombia{
    object Entrenador2{
        "Entrenador 2"
    }

    package integrantes1 {
        object Jugador7{
            "pepe1"
            213123123
            La Guaira
        }
        object Jugador8{
            "pepe2"
            213123123
            La Guaira
        }
        object Jugador9{
            "pepe3"
            213123123
            La Guaira
        }
        object Jugador10{
            "pepe4"
            213123123
            La Guaira
        }
        object Jugador11{
            "pepe5"
            213123123
            La Guaira
        }
        object Capitan12{
            "pepe6"
            213123123
            La Guaira
        }
    }
}
'/
map Juego {
    Venezuela =>
    Colombia =>
    Lugar => Santiago de Chile
}
object Venezuela{
    -Nombre = "Equipo 1"
    -pais = Venezuela
}
object Colombia{
    -Nombre = "Equipo 2"
    -Pais = colombia
}

Juego *-- Venezuela
Juego *-- Colombia

object LosPanamericanos {
    - Titulo = "Chile 2023"
}
LosPanamericanos *-- Juego


object EntrenadorV {
    Nivel = 5
    experiencia = 25
}


object EntrenadorC {
    Nivel = 5
    experiencia = 25
}

EntrenadorV *-- Venezuela
EntrenadorC *-- Colombia

object J1 {
    "o1"
    "042412123123"
    "La Guaira"
    "numero 1"
    "Posicion 1"
}

object J2 {
    "o2"
    "042412123123"
    "La Guaira"
    "numero 2"
    "Posicion 2"
}

object J3 {
    "o3"
    "042412123123"
    "La Guaira"
    "numero 3"
    "Posicion 3"
}

object J4 {
    "o4"
    "042412123123"
    "La Guaira"
    "numero 4"
    "Posicion 4"
}

object J5 {
    "o5"
    "042412123123"
    "La Guaira"
    "numero 5"
    "Posicion 5"
}

object C6 {
    "o6"
    "042412123123"
    "La Guaira"
    "numero 6"
    "Posicion 6"
}

object J7 {
    "o7"
    "042412123123"
    "La Guaira"
    "numero 7"
    "Posicion 1"
}

object J8 {
    "o8"
    "042412123123"
    "La Guaira"
    "numero 8"
    "Posicion 2"
}

object J9 {
    "o9"
    "042412123123"
    "La Guaira"
    "numero 9"
    "Posicion 3"
}

object J10 {
    "o10"
    "042412123123"
    "La Guaira"
    "numero 10"
    "Posicion 4"
}

object J11 {
    "o11"
    "042412123123"
    "La Guaira"
    "numero 11"
    "Posicion 5"
}

object C12 {
    "o12"
    "042412123123"
    "La Guaira"
    "numero 12"
    "Posicion 6"
}

Venezuela *-- J1
Venezuela *-- J2
Venezuela *-- J3
Venezuela *-- J4
Venezuela *-- J5
Venezuela *-- C6

Colombia *-- J7
Colombia *-- J8
Colombia *-- J9
Colombia *-- J10
Colombia *-- J11
Colombia *-- C12

@enduml