@startuml practica2_reto_f

header "Representacion de clases"
title "Juegos Panamericanos"
    

abstract Persona  {
    -nombre
    -telefono
    -direccion
} 
class Entrenador{
    -nivel
    -experiencia
}

class Juego {
    -Localidad
    -Puntuacion
}

class Equipo{
    -nombre
    -pais

}

class Registro {
    -idJugador
    -Record
}

class Jugador {
    -numero
    -posicion
}

Class Capitan

Equipo "1" o-right-"6..20" Jugador: Parte de <
Equipo *--  Registro
Persona <|-- Jugador
Persona <|-left- Entrenador: Hereda de <
Juego "1" *-right- "2" Equipo: Parte de un <
Equipo "<b>*" *-up- "<b> 1 " Entrenador: Compone a <
Competencia *-- Juego
Capitan --|> Jugador: Hereda de > 
Capitan "1" --* "1" Equipo: Compone a >

newpage 
'left to right direction
'right to left direccion

package Venezuela{
    object Entrenador{
        "Entrenador 1"
    }

    package integrantes {
        object Jugador1{
            "pepe1"
            213123123
            La Guaira
        }
        object Jugador2{
            "pepe2"
            213123123
            La Guaira
        }
        object Jugador3{
            "pepe3"
            213123123
            La Guaira
        }
        object Jugador4{
            "pepe4"
            213123123
            La Guaira
        }
        object Jugador5{
            "pepe5"
            213123123
            La Guaira
        }
        object Capitan6{
            "pepe6"
            213123123
            La Guaira
        }
    }
}


package Colombia{
    object Entrenador2{
        "Entrenador 2"
    }

    package integrantes1 {
        object Jugador7{
            "pepe1"
            213123123
            La Guaira
        }
        object Jugador8{
            "pepe2"
            213123123
            La Guaira
        }
        object Jugador9{
            "pepe3"
            213123123
            La Guaira
        }
        object Jugador10{
            "pepe4"
            213123123
            La Guaira
        }
        object Jugador11{
            "pepe5"
            213123123
            La Guaira
        }
        object Capitan12{
            "pepe6"
            213123123
            La Guaira
        }
    }
}

map Juego {
    Venezuela =>
    Colombia =>
    Lugar => Santiago de Chile
}

Juego::Equipo1 ..> Venezuela
Juego::Equipo2 ..> Colombia

object LosPanamericanos {
    - Titulo = "Chile 2023"
}
LosPanamericanos *-- Juego


@enduml